# Adding New Colums

In [1]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [2]:
# adding a column with constant value 

df['Country'] = 'Bangladesh'

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka,Bangladesh
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet,Bangladesh
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram,Bangladesh
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka,Bangladesh
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna,Bangladesh
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi,Bangladesh
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka,Bangladesh
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet,Bangladesh
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram,Bangladesh
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka,Bangladesh
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna,Bangladesh
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi,Bangladesh
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka,Bangladesh
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram,Bangladesh
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet,Bangladesh
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi,Bangladesh
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka,Bangladesh
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram,Bangladesh
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna,Bangladesh
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka,Bangladesh
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet,Bangladesh
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi,Bangladesh
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka,Bangladesh
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram,Bangladesh
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna,Bangladesh
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka,Bangladesh
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet,Bangladesh
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi,Bangladesh
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka,Bangladesh
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram,Bangladesh
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna,Bangladesh
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet,Bangladesh
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka,Bangladesh
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi,Bangladesh
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka,Bangladesh
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram,Bangladesh
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna,Bangladesh
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet,Bangladesh
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka,Bangladesh
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi,Bangladesh
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram,Bangladesh
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka,Bangladesh
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna,Bangladesh
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet,Bangladesh

In [4]:
df['Total Marks'] = df['Data Structure Marks'] + df['Python Marks'] + df['Algorithm Marks']
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka,Bangladesh,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet,Bangladesh,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram,Bangladesh,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka,Bangladesh,261.0
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna,Bangladesh,240.0
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi,Bangladesh,275.0
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka,Bangladesh,210.0
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet,Bangladesh,288.0
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram,Bangladesh,249.0
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka,Bangladesh,231.0
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna,Bangladesh,NaN
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi,Bangladesh,261.0
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka,Bangladesh,222.0
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram,Bangladesh,280.0
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet,Bangladesh,247.0
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi,Bangladesh,NaN
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka,Bangladesh,207.0
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram,Bangladesh,294.0
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna,Bangladesh,249.0
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka,Bangladesh,222.0
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet,Bangladesh,272.0
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi,Bangladesh,NaN
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka,Bangladesh,243.0
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram,Bangladesh,237.0
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna,Bangladesh,261.0
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka,Bangladesh,277.0
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet,Bangladesh,202.0
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi,Bangladesh,285.0
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka,Bangladesh,231.0
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram,Bangladesh,252.0
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna,Bangladesh,NaN
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet,Bangladesh,264.0
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka,Bangladesh,273.0
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi,Bangladesh,219.0
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka,Bangladesh,258.0
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram,Bangladesh,282.0
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna,Bangladesh,NaN
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet,Bangladesh,246.0
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka,Bangladesh,206.0
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi,Bangladesh,291.0
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram,Bangladesh,255.0
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka,Bangladesh,NaN
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna,Bangladesh,228.0
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet,Bangladesh,270.0

In [5]:
import numpy as np 

df['A+ in DS'] = np.where(df['Data Structure Marks']>90, 'A+' , 'A')

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram,Bangladesh,NaN,A
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna,Bangladesh,240.0,A
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi,Bangladesh,275.0,A+
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka,Bangladesh,210.0,A
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet,Bangladesh,288.0,A+
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram,Bangladesh,249.0,A
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka,Bangladesh,231.0,A
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna,Bangladesh,NaN,A
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi,Bangladesh,261.0,A
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka,Bangladesh,222.0,A
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram,Bangladesh,280.0,A+
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet,Bangladesh,247.0,A
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi,Bangladesh,NaN,A
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka,Bangladesh,207.0,A
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram,Bangladesh,294.0,A+
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna,Bangladesh,249.0,A
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka,Bangladesh,222.0,A
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet,Bangladesh,272.0,A
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi,Bangladesh,NaN,A
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka,Bangladesh,243.0,A
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram,Bangladesh,237.0,A
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna,Bangladesh,261.0,A
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka,Bangladesh,277.0,A+
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet,Bangladesh,202.0,A
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi,Bangladesh,285.0,A+
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka,Bangladesh,231.0,A
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram,Bangladesh,252.0,A
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna,Bangladesh,NaN,A
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet,Bangladesh,264.0,A
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka,Bangladesh,273.0,A
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi,Bangladesh,219.0,A
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka,Bangladesh,258.0,A
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram,Bangladesh,282.0,A+
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna,Bangladesh,NaN,A
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet,Bangladesh,246.0,A
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka,Bangladesh,206.0,A
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi,Bangladesh,291.0,A+
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram,Bangladesh,255.0,A
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka,Bangladesh,NaN,A
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna,Bangladesh,228.0,A
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet,Bangladesh,270.0,A

In [7]:
df['Passed in DS'] = df['Data Structure Marks'] >70

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna,Bangladesh,240.0,A,True
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi,Bangladesh,275.0,A+,True
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka,Bangladesh,210.0,A,False
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet,Bangladesh,288.0,A+,True
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram,Bangladesh,249.0,A,True
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka,Bangladesh,231.0,A,True
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna,Bangladesh,NaN,A,False
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi,Bangladesh,261.0,A,True
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka,Bangladesh,222.0,A,True
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram,Bangladesh,280.0,A+,True
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet,Bangladesh,247.0,A,True
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi,Bangladesh,NaN,A,True
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka,Bangladesh,207.0,A,False
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram,Bangladesh,294.0,A+,True
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna,Bangladesh,249.0,A,True
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka,Bangladesh,222.0,A,True
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet,Bangladesh,272.0,A,True
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi,Bangladesh,NaN,A,False
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka,Bangladesh,243.0,A,True
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram,Bangladesh,237.0,A,True
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna,Bangladesh,261.0,A,True
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka,Bangladesh,277.0,A+,True
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet,Bangladesh,202.0,A,False
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi,Bangladesh,285.0,A+,True
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka,Bangladesh,231.0,A,True
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram,Bangladesh,252.0,A,True
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna,Bangladesh,NaN,A,False
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet,Bangladesh,264.0,A,True
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka,Bangladesh,273.0,A,True
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi,Bangladesh,219.0,A,True
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka,Bangladesh,258.0,A,True
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram,Bangladesh,282.0,A+,True
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna,Bangladesh,NaN,A,True
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet,Bangladesh,246.0,A,True
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka,Bangladesh,206.0,A,False
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi,Bangladesh,291.0,A+,True
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram,Bangladesh,255.0,A,True
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka,Bangladesh,NaN,A,False
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna,Bangladesh,228.0,A,True
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet,Bangladesh,270.0,A,True

In [8]:
df['First Name'] = df['FullName'].str.split(' ').str[0]

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna,Bangladesh,240.0,A,True,Sabbir
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi,Bangladesh,275.0,A+,True,Ruby
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka,Bangladesh,210.0,A,False,Hasibul
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet,Bangladesh,288.0,A+,True,Mehjabin
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram,Bangladesh,249.0,A,True,Shakib
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka,Bangladesh,231.0,A,True,Nusrat
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna,Bangladesh,NaN,A,False,Rakib
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi,Bangladesh,261.0,A,True,Mim
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka,Bangladesh,222.0,A,True,Touhid
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram,Bangladesh,280.0,A+,True,Farzana
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet,Bangladesh,247.0,A,True,Anik
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi,Bangladesh,NaN,A,True,Sumaiya
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka,Bangladesh,207.0,A,False,Minhaz
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram,Bangladesh,294.0,A+,True,Raisa
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna,Bangladesh,249.0,A,True,Arif
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka,Bangladesh,222.0,A,True,Jubayer
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet,Bangladesh,272.0,A,True,Samira
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi,Bangladesh,NaN,A,False,Rifat
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka,Bangladesh,243.0,A,True,Tanjina
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram,Bangladesh,237.0,A,True,Ashikur
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna,Bangladesh,261.0,A,True,Nayeem
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka,Bangladesh,277.0,A+,True,Sanjida
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet,Bangladesh,202.0,A,False,Rezaul
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi,Bangladesh,285.0,A+,True,Lamia
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka,Bangladesh,231.0,A,True,Saiful
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram,Bangladesh,252.0,A,True,Tamanna
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna,Bangladesh,NaN,A,False,Israt
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet,Bangladesh,264.0,A,True,Muntasir
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Nabila
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi,Bangladesh,219.0,A,True,Shuvo
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka,Bangladesh,258.0,A,True,Maruf
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram,Bangladesh,282.0,A+,True,Sadia
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna,Bangladesh,NaN,A,True,Tariqul
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet,Bangladesh,246.0,A,True,Sharmin
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka,Bangladesh,206.0,A,False,Emon
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi,Bangladesh,291.0,A+,True,Mahira
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram,Bangladesh,255.0,A,True,Sakib
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka,Bangladesh,NaN,A,False,Nafisa
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna,Bangladesh,228.0,A,True,Shihab
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet,Bangladesh,270.0,A,True,Rumana

In [9]:
df1 = pd.read_csv('student_data.csv')
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet