# Unique and nunique

In [ ]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     85
4    David     Tokyo     95
5      Bob    London     90

In [74]:
# unique works on only series 
df['Name'].unique()

df['Name'].unique()

array(['Alice', 'Bob', 'Charlie', 'David'], dtype=object)

In [75]:
df1 = pd.read_csv('student_data.csv')


df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [76]:
len(df1['Data Structure Marks'].unique())

df1['Data Structure Marks'].nunique()

30

In [77]:
df.nunique()

Name     4
City     4
Score    4
dtype: int64

# Check null

In [78]:
df1.isnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,True,True,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,True,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,True,True,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False
46,False,False,True,True,True,False,False,False,False
47,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False
52,False,False,False,False,True,False,False,False,False
53,False,False,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,False,False
57,False,False,True,True,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False

In [79]:
df1['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46     True
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57     True
58    False
59    False
Name: Data Structure Marks, dtype: bool

In [80]:
df1['Data Structure Marks'].notnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26    False
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37    False
38     True
39     True
40     True
41     True
42     True
43     True
44     True
45     True
46    False
47     True
48     True
49     True
50     True
51     True
52     True
53     True
54     True
55     True
56     True
57    False
58     True
59     True
Name: Data Structure Marks, dtype: bool

In [81]:
df1['Data Structure Marks'].hasnans

True

In [82]:
df1['StudentID'].hasnans

False

In [83]:
df1[['FullName','StudentID']]

            FullName StudentID
0        Alif Rahman    PH1001
1      Fatima Akhter    PH1002
2      Imran Hossain    PH1003
3   Jannatul Ferdous    PH1004
4        Kamal Uddin    PH1005
5        Laila Begum    PH1006
6     Mahmudul Hasan    PH1007
7        Nadia Islam    PH1008
8         Omar Faruq    PH1009
9       Priya Sharma    PH1010
10      Rahim Sheikh    PH1011
11   Sadia Chowdhury    PH1012
12      Tanvir Ahmed    PH1013
13        Urmi Akter    PH1014
14      Wahiduzzaman    PH1015
15      Ziaur Rahman    PH1016
16       Afsana Mimi    PH1017
17       Babul Ahmed    PH1018
18      Faria Rahman    PH1019
19        Nasir Khan    PH1020
20      Sabbir Hasan    PH1021
21        Ruby Akter    PH1022
22     Hasibul Islam    PH1023
23     Mehjabin Noor    PH1024
24   Shakib Al Hasan    PH1025
25      Nusrat Jahan    PH1026
26       Rakib Ahmed    PH1027
27        Mim Rahman    PH1028
28      Touhid Hasan    PH1029
29    Farzana Yasmin    PH1030
30       Anik Sarker    PH1031
31     Sumaiya Akter    PH1032
32      Minhaz Uddin    PH1033
33       Raisa Islam    PH1034
34    Arif Chowdhury    PH1035
35   Jubayer Hossain    PH1036
36       Samira Khan    PH1037
37       Rifat Ahmed    PH1038
38      Tanjina Noor    PH1039
39    Ashikur Rahman    PH1040
40      Nayeem Hasan    PH1041
41     Sanjida Akter    PH1042
42      Rezaul Karim    PH1043
43      Lamia Jannat    PH1044
44      Saiful Islam    PH1045
45    Tamanna Rahman    PH1046
46       Israt Jahan    PH1047
47    Muntasir Ahmed    PH1048
48       Nabila Noor    PH1049
49         Shuvo Das    PH1050
50       Maruf Hasan    PH1051
51      Sadia Rahman    PH1052
52     Tariqul Islam    PH1053
53     Sharmin Akter    PH1054
54      Emon Hossain    PH1055
55       Mahira Khan    PH1056
56      Sakib Mahmud    PH1057
57      Nafisa Islam    PH1058
58      Shihab Uddin    PH1059
59     Rumana Yasmin    PH1060

# Handling Duplicates Values

In [84]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [85]:
df.duplicated().sum()

np.int64(1)

In [86]:
# delelting duplicates values 

df.drop_duplicates()

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [87]:
# permanent 

df.drop_duplicates(inplace= True)

In [88]:
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [89]:
# name er basis e duplicate deletion 

df.drop_duplicates(subset=['Name'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [90]:
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [91]:
# city
df.drop_duplicates(subset=['City'])

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [92]:
df.drop_duplicates(subset=['Name'],keep='last')

      Name      City  Score
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [93]:
df.drop_duplicates(subset=['Name'],keep='first')

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

# Handling Null values

In [94]:
df = pd.read_csv('student_data.csv')

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [95]:
df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [96]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [97]:
df.dropna(how='all',inplace = True)

In [98]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [99]:
df.dropna(subset=['Python Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [100]:
df.dropna(subset=['Python Marks','Algorithm Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [101]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [102]:
df.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,0.0,0.0,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,0.0,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,0.0,0.0,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,0.0,0.0,0.0,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,0.0,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,0.0,0.0,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [103]:
df = pd.read_csv('student_data.csv')

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,NaN,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,NaN,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,NaN,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [104]:
df.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.0,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.0,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.0,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.0,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.0,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.0,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,0.0,0.0,88.0,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.0,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.0,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.0,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.0,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,0.0,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.0,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.0,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.0,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.0,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.0,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,0.0,0.0,90.0,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.0,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.0,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.0,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.0,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.0,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.0,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.0,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.0,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,0.0,0.0,0.0,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.0,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.0,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.0,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.0,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.0,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,0.0,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.0,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.0,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.0,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.0,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,0.0,0.0,88.0,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.0,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.0,Completed,2025-08-01,Mr. David,Sylhet

In [105]:
df['FullName'].fillna('unknown')

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20        Sabbir Hasan
21          Ruby Akter
22       Hasibul Islam
23       Mehjabin Noor
24     Shakib Al Hasan
25        Nusrat Jahan
26         Rakib Ahmed
27          Mim Rahman
28        Touhid Hasan
29      Farzana Yasmin
30         Anik Sarker
31       Sumaiya Akter
32        Minhaz Uddin
33         Raisa Islam
34      Arif Chowdhury
35     Jubayer Hossain
36         Samira Khan
37         Rifat Ahmed
38        Tanjina Noor
39      Ashikur Rahman
40        Nayeem Hasan
41       Sanjida Akter
42        Rezaul Karim
43        Lamia Jannat
44        Saiful Islam
45      Tamanna Rahman
46         Israt Jahan
47      Muntasir Ahmed
48         Nabila Noor
49           Shuvo Das
50         Maruf Hasan
51        Sadia Rahman
52       Tariqul Islam
53       Sharmin Akter
54        Emon Hossain
55         Mahira Khan
56        Sakib Mahmud
57        Nafisa Islam
58        Shihab Uddin
59       Rumana Yasmin
Name: FullName, dtype: object

In [106]:
df['Python Marks'].fillna(df['Python Marks'].mean(),inplace=True)

/tmp/ipykernel_7600/3283531364.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Python Marks'].fillna(df['Python Marks'].mean(),inplace=True)

In [107]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet

# Statistical Functions

In [108]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet

In [109]:
df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet

In [110]:
# sum
df['Data Structure Marks'].sum()

np.float64(4321.0)

In [111]:
# max and min 
print(df['Data Structure Marks'].min())
df['Data Structure Marks'].max()

65.0

97.0

In [112]:
#mean -> average 

df['Data Structure Marks'].mean()

np.float64(83.09615384615384)

In [113]:
#median 
df['Data Structure Marks'].median()

84.5

In [114]:
# mode -> highest frequency er number 

df['Data Structure Marks'].mode()

0    85.0
1    88.0
Name: Data Structure Marks, dtype: float64

In [115]:
# standard deviation -> std 
df['Data Structure Marks'].std()

8.059240501813019

In [116]:
# correlation matrix 

df[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.937606
Python Marks                      0.937606      1.000000

In [117]:
# sum in different columns row wise
df[['Data Structure Marks','Python Marks']].sum(axis=1)

0     173.000000
1     177.076923
2     173.000000
3     160.000000
4      95.000000
5     153.000000
6     165.076923
7     166.000000
8     148.000000
9     177.000000
10     91.000000
11    172.000000
12    154.000000
13     85.076923
14    170.000000
15    179.076923
16    183.000000
17    173.000000
18     85.076923
19    175.000000
20    159.000000
21    185.000000
22    140.000000
23    192.000000
24    165.000000
25    155.000000
26     88.000000
27    174.000000
28    147.000000
29    187.000000
30    165.000000
31    173.076923
32    137.000000
33    196.000000
34    166.000000
35    148.000000
36    181.000000
37     90.000000
38    161.000000
39    158.000000
40    173.000000
41    185.000000
42    135.000000
43    190.000000
44    154.000000
45    168.000000
46     85.076923
47    177.000000
48    182.000000
49    146.000000
50    172.000000
51    188.000000
52    164.076923
53    164.000000
54    137.000000
55    194.000000
56    170.000000
57     88.000000
58    152.000000
59    180.000000
dtype: float64

In [118]:
df['Total Marks'] = df.iloc[::,2:5].sum(axis=1)

In [119]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram,269.076923
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka,245.076923
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.076923
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram,273.076923
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram,85.076923
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka,261.000000
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna,240.000000
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi,275.000000
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka,210.000000
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet,288.000000
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram,249.000000
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka,231.000000
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna,88.000000
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi,261.000000
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka,222.000000
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram,280.000000
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet,247.000000
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi,263.076923
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka,207.000000
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram,294.000000
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna,249.000000
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka,222.000000
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet,272.000000
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi,90.000000
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka,243.000000
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram,237.000000
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna,261.000000
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka,277.000000
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet,202.000000
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi,285.000000
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka,231.000000
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram,252.000000
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna,85.076923
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet,264.000000
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka,273.000000
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi,219.000000
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka,258.000000
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram,282.000000
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna,244.076923
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet,246.000000
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka,206.000000
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi,291.000000
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram,255.000000
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka,88.000000
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna,228.000000
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet,270.000000

In [120]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  Total Marks
count             52.000000        52.000000     60.000000    60.000000
mean              83.096154        83.807692     85.076923   229.726923
std                8.059241         7.921276      7.294870    59.945145
min               65.000000        67.000000     68.000000    85.076923
25%               77.750000        77.750000     80.750000   222.000000
50%               84.500000        85.000000     85.076923   248.000000
75%               89.000000        90.000000     89.250000   264.500000
max               97.000000        98.000000     99.000000   294.000000

In [121]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram,269.076923
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka,245.076923
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.076923
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram,273.076923
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram,85.076923
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka,261.000000
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna,240.000000
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi,275.000000
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka,210.000000
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet,288.000000
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram,249.000000
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka,231.000000
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna,88.000000
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi,261.000000
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka,222.000000
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram,280.000000
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet,247.000000
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi,263.076923
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka,207.000000
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram,294.000000
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna,249.000000
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka,222.000000
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet,272.000000
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi,90.000000
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka,243.000000
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram,237.000000
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna,261.000000
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka,277.000000
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet,202.000000
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi,285.000000
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka,231.000000
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram,252.000000
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna,85.076923
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet,264.000000
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka,273.000000
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi,219.000000
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka,258.000000
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram,282.000000
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna,244.076923
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet,246.000000
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka,206.000000
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi,291.000000
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram,255.000000
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka,88.000000
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna,228.000000
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet,270.000000

# apply function on df

In [122]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram,269.076923
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka,245.076923
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.076923
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram,273.076923
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram,85.076923
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka,261.000000
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna,240.000000
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi,275.000000
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka,210.000000
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet,288.000000
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram,249.000000
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka,231.000000
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna,88.000000
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi,261.000000
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka,222.000000
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram,280.000000
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet,247.000000
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi,263.076923
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka,207.000000
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram,294.000000
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna,249.000000
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka,222.000000
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet,272.000000
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi,90.000000
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka,243.000000
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram,237.000000
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna,261.000000
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka,277.000000
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet,202.000000
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi,285.000000
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka,231.000000
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram,252.000000
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna,85.076923
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet,264.000000
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka,273.000000
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi,219.000000
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka,258.000000
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram,282.000000
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna,244.076923
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet,246.000000
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka,206.000000
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi,291.000000
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram,255.000000
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka,88.000000
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna,228.000000
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet,270.000000

In [123]:
#min max scaling 

mn = df['Total Marks'].min() 
mx = df['Total Marks'].max() 


df['Scaled Marks'] = df['Total Marks'].apply(lambda x : (x-mn)/(mx-mn))

In [124]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.827688
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram,269.076923,0.880707
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.842047
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.731959
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.047496
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.684094
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka,245.076923,0.765832
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.775037
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.645803
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.865979
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028351
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.822901
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.688881
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.076923,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.818115
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram,273.076923,0.899853
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka,273.000000,0.899485
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet,261.000000,0.842047
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram,85.076923,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka,261.000000,0.842047
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna,240.000000,0.741532
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi,275.000000,0.909057
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka,210.000000,0.597938
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet,288.000000,0.971281
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram,249.000000,0.784610
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka,231.000000,0.698454
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna,88.000000,0.013991
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi,261.000000,0.842047
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka,222.000000,0.655376
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram,280.000000,0.932990
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet,247.000000,0.775037
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi,263.076923,0.851988
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka,207.000000,0.583579
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram,294.000000,1.000000
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna,249.000000,0.784610
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka,222.000000,0.655376
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet,272.000000,0.894698
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi,90.000000,0.023564
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka,243.000000,0.755891
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram,237.000000,0.727172
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna,261.000000,0.842047
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka,277.000000,0.918630
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet,202.000000,0.559647
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi,285.000000,0.956922
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka,231.000000,0.698454
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram,252.000000,0.798969
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna,85.076923,0.000000
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet,264.000000,0.856406
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka,273.000000,0.899485
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi,219.000000,0.641016
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka,258.000000,0.827688
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram,282.000000,0.942563
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna,244.076923,0.761046
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet,246.000000,0.770250
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka,206.000000,0.578792
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi,291.000000,0.985641
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram,255.000000,0.813328
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka,88.000000,0.013991
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna,228.000000,0.684094
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet,270.000000,0.885125

In [125]:
# custom built function 

def grading_system(marks):

    if marks >=260:
        return 'A+' 
    elif marks>=250:
        return 'A' 
    else:
        return 'A-'


df['Grade'] = df['Total Marks'].apply(grading_system)

In [126]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.827688,A
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram,269.076923,0.880707,A+
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.842047,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.731959,A-
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.047496,A-
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.684094,A-
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka,245.076923,0.765832,A-
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.775037,A-
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.645803,A-
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.865979,A+
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028351,A-
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.822901,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.688881,A-
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.076923,0.000000,A-
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.818115,A
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram,273.076923,0.899853,A+
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka,273.000000,0.899485,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet,261.000000,0.842047,A+
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram,85.076923,0.000000,A-
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka,261.000000,0.842047,A+
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna,240.000000,0.741532,A-
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi,275.000000,0.909057,A+
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka,210.000000,0.597938,A-
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet,288.000000,0.971281,A+
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram,249.000000,0.784610,A-
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka,231.000000,0.698454,A-
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna,88.000000,0.013991,A-
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi,261.000000,0.842047,A+
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka,222.000000,0.655376,A-
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram,280.000000,0.932990,A+
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet,247.000000,0.775037,A-
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi,263.076923,0.851988,A+
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka,207.000000,0.583579,A-
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram,294.000000,1.000000,A+
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna,249.000000,0.784610,A-
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka,222.000000,0.655376,A-
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet,272.000000,0.894698,A+
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi,90.000000,0.023564,A-
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka,243.000000,0.755891,A-
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram,237.000000,0.727172,A-
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna,261.000000,0.842047,A+
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka,277.000000,0.918630,A+
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet,202.000000,0.559647,A-
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi,285.000000,0.956922,A+
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka,231.000000,0.698454,A-
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram,252.000000,0.798969,A
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna,85.076923,0.000000,A-
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet,264.000000,0.856406,A+
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka,273.000000,0.899485,A+
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi,219.000000,0.641016,A-
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka,258.000000,0.827688,A
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram,282.000000,0.942563,A+
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna,244.076923,0.761046,A-
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet,246.000000,0.770250,A-
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka,206.000000,0.578792,A-
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi,291.000000,0.985641,A+
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram,255.000000,0.813328,A
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka,88.000000,0.013991,A-
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna,228.000000,0.684094,A-
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet,270.000000,0.885125,A+

In [127]:
def marking_system(df): 
    a = df['Data Structure Marks'] * 2 
    b = df['Python Marks'] * 3 
    c = df['Algorithm Marks'] * 4

    return a+b+c 



df['Exceptional Marks'] = df.apply(marking_system,axis=1)

In [128]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks
0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,258.000000,0.827688,A,774.000000
1,PH1002,Fatima Akhter,92.0,92.0,85.076923,In Progress,2024-01-20,Ms. Salma,Chattogram,269.076923,0.880707,A+,807.230769
2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,261.000000,0.842047,A+,783.000000
3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,238.000000,0.731959,A-,714.000000
4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,95.000000,0.047496,A-,NaN
5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,228.000000,0.684094,A-,684.000000
6,PH1007,Mahmudul Hasan,80.0,80.0,85.076923,In Progress,2024-04-01,Mr. Karim,Dhaka,245.076923,0.765832,A-,735.230769
7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,247.000000,0.775037,A-,741.000000
8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,220.000000,0.645803,A-,660.000000
9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,266.000000,0.865979,A+,798.000000
10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,91.000000,0.028351,A-,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,257.000000,0.822901,A,771.000000
12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,229.000000,0.688881,A-,687.000000
13,PH1014,Urmi Akter,NaN,NaN,85.076923,Not Started,2024-07-09,Ms. Salma,Rajshahi,85.076923,0.000000,A-,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,256.000000,0.818115,A,768.000000
15,PH1016,Ziaur Rahman,94.0,94.0,85.076923,In Progress,2024-08-21,Ms. Salma,Chattogram,273.076923,0.899853,A+,819.230769
16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2024-09-01,Mr. Karim,Dhaka,273.000000,0.899485,A+,819.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2024-09-05,Ms. Salma,Sylhet,261.000000,0.842047,A+,783.000000
18,PH1019,Faria Rahman,NaN,NaN,85.076923,Not Started,2024-09-15,Mr. David,Chattogram,85.076923,0.000000,A-,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2024-10-02,Ms. Salma,Dhaka,261.000000,0.842047,A+,783.000000
20,PH1021,Sabbir Hasan,79.0,81.0,80.000000,Completed,2024-10-10,Mr. Karim,Khulna,240.000000,0.741532,A-,722.000000
21,PH1022,Ruby Akter,91.0,90.0,94.000000,Completed,2024-10-15,Ms. Salma,Rajshahi,275.000000,0.909057,A+,824.000000
22,PH1023,Hasibul Islam,68.0,70.0,72.000000,In Progress,2024-11-01,Mr. David,Dhaka,210.000000,0.597938,A-,632.000000
23,PH1024,Mehjabin Noor,95.0,96.0,97.000000,Completed,2024-11-11,Ms. Salma,Sylhet,288.000000,0.971281,A+,865.000000
24,PH1025,Shakib Al Hasan,82.0,84.0,83.000000,Completed,2024-11-15,Mr. Karim,Chattogram,249.000000,0.784610,A-,749.000000
25,PH1026,Nusrat Jahan,77.0,76.0,78.000000,Completed,2024-12-01,Ms. Salma,Dhaka,231.000000,0.698454,A-,692.000000
26,PH1027,Rakib Ahmed,NaN,NaN,88.000000,In Progress,2024-12-05,Mr. David,Khulna,88.000000,0.013991,A-,NaN
27,PH1028,Mim Rahman,85.0,87.0,89.000000,Completed,2024-12-20,Mr. Karim,Rajshahi,261.000000,0.842047,A+,785.000000
28,PH1029,Touhid Hasan,74.0,75.0,73.000000,Completed,2025-01-03,Ms. Salma,Dhaka,222.000000,0.655376,A-,667.000000
29,PH1030,Farzana Yasmin,92.0,93.0,95.000000,Completed,2025-01-08,Mr. Karim,Chattogram,280.000000,0.932990,A+,841.000000
30,PH1031,Anik Sarker,81.0,82.0,84.000000,Completed,2025-01-20,Mr. David,Sylhet,247.000000,0.775037,A-,742.000000
31,PH1032,Sumaiya Akter,88.0,90.0,85.076923,In Progress,2025-02-01,Ms. Salma,Rajshahi,263.076923,0.851988,A+,791.230769
32,PH1033,Minhaz Uddin,69.0,70.0,68.000000,Completed,2025-02-05,Mr. Karim,Dhaka,207.000000,0.583579,A-,622.000000
33,PH1034,Raisa Islam,97.0,98.0,99.000000,Completed,2025-02-11,Ms. Salma,Chattogram,294.000000,1.000000,A+,883.000000
34,PH1035,Arif Chowdhury,84.0,83.0,82.000000,Completed,2025-02-18,Mr. David,Khulna,249.000000,0.784610,A-,746.000000
35,PH1036,Jubayer Hossain,73.0,74.0,75.000000,Completed,2025-03-02,Mr. Karim,Dhaka,222.000000,0.655376,A-,667.000000
36,PH1037,Samira Khan,89.0,91.0,92.000000,Completed,2025-03-08,Ms. Salma,Sylhet,272.000000,0.894698,A+,818.000000
37,PH1038,Rifat Ahmed,NaN,NaN,90.000000,In Progress,2025-03-15,Mr. David,Rajshahi,90.000000,0.023564,A-,NaN
38,PH1039,Tanjina Noor,80.0,82.0,81.000000,Completed,2025-03-20,Mr. Karim,Dhaka,243.000000,0.755891,A-,731.000000
39,PH1040,Ashikur Rahman,78.0,79.0,80.000000,Completed,2025-04-01,Ms. Salma,Chattogram,237.000000,0.727172,A-,712.000000
40,PH1041,Nayeem Hasan,87.0,88.0,86.000000,Completed,2025-04-05,Mr. Karim,Khulna,261.000000,0.842047,A+,784.000000
41,PH1042,Sanjida Akter,91.0,92.0,94.000000,Completed,2025-04-11,Ms. Salma,Dhaka,277.000000,0.918630,A+,832.000000
42,PH1043,Rezaul Karim,65.0,67.0,70.000000,In Progress,2025-04-15,Mr. David,Sylhet,202.000000,0.559647,A-,608.000000
43,PH1044,Lamia Jannat,94.0,95.0,96.000000,Completed,2025-04-20,Mr. Karim,Rajshahi,285.000000,0.956922,A+,856.000000
44,PH1045,Saiful Islam,76.0,77.0,78.000000,Completed,2025-05-01,Ms. Salma,Dhaka,231.000000,0.698454,A-,694.000000
45,PH1046,Tamanna Rahman,83.0,84.0,85.000000,Completed,2025-05-05,Mr. Karim,Chattogram,252.000000,0.798969,A,757.000000
46,PH1047,Israt Jahan,NaN,NaN,85.076923,Not Started,2025-05-10,Mr. David,Khulna,85.076923,0.000000,A-,NaN
47,PH1048,Muntasir Ahmed,88.0,87.0,89.000000,Completed,2025-05-18,Ms. Salma,Sylhet,264.000000,0.856406,A+,791.000000
48,PH1049,Nabila Noor,90.0,91.0,92.000000,Completed,2025-05-25,Mr. Karim,Dhaka,273.000000,0.899485,A+,820.000000
49,PH1050,Shuvo Das,72.0,73.0,74.000000,Completed,2025-06-01,Ms. Salma,Rajshahi,219.000000,0.641016,A-,658.000000
50,PH1051,Maruf Hasan,85.0,86.0,87.000000,Completed,2025-06-07,Mr. David,Dhaka,258.000000,0.827688,A,775.000000
51,PH1052,Sadia Rahman,93.0,94.0,95.000000,Completed,2025-06-14,Mr. Karim,Chattogram,282.000000,0.942563,A+,847.000000
52,PH1053,Tariqul Islam,79.0,80.0,85.076923,In Progress,2025-06-18,Ms. Salma,Khulna,244.076923,0.761046,A-,733.230769
53,PH1054,Sharmin Akter,81.0,82.0,83.000000,Completed,2025-06-25,Mr. David,Sylhet,246.000000,0.770250,A-,739.000000
54,PH1055,Emon Hossain,67.0,69.0,70.000000,Completed,2025-07-02,Mr. Karim,Dhaka,206.000000,0.578792,A-,620.000000
55,PH1056,Mahira Khan,96.0,97.0,98.000000,Completed,2025-07-08,Ms. Salma,Rajshahi,291.000000,0.985641,A+,874.000000
56,PH1057,Sakib Mahmud,84.0,85.0,86.000000,Completed,2025-07-12,Mr. David,Chattogram,255.000000,0.813328,A,766.000000
57,PH1058,Nafisa Islam,NaN,NaN,88.000000,In Progress,2025-07-18,Mr. Karim,Dhaka,88.000000,0.013991,A-,NaN
58,PH1059,Shihab Uddin,75.0,76.0,77.000000,Completed,2025-07-22,Ms. Salma,Khulna,228.000000,0.684094,A-,685.000000
59,PH1060,Rumana Yasmin,89.0,90.0,91.000000,Completed,2025-08-01,Mr. David,Sylhet,270.000000,0.885125,A+,811.000000

# datetime and time delta

In [129]:
df = pd.read_csv('student_completed_data.csv')
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [130]:
df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [131]:
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])

In [132]:
df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

In [133]:
df['Enrollment Year'] = df['EnrollmentDate'].dt.year

In [134]:
df['Enrollment Date'] = df['EnrollmentDate'].dt.day

In [135]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Date
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,1
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,11
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,8
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,5
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,1
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,7
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,7
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,22
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,12
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,19
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,14
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,4
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,7
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,4
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,22
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,23
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,18
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,23
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,19
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,21

In [136]:
df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])

In [137]:
df['Total time taken to finish']= df['FinishedDate'] - df['EnrollmentDate']

In [138]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,1,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,11,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,8,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,5,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,1,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,7,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,7,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,22,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,12,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,19,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,14,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,4,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,7,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,4,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,22,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,23,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,18,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,23,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,19,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,21,82 days

# Groupby

In [139]:
import numpy as np

df.loc[df['FullName'] == 'Afsana Mimi', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Sadia Chowdhury', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Alif Rahman', 'Total Marks'] = np.nan

In [140]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN,2024,1,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0,2024,11,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0,2024,8,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0,2024,5,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0,2024,1,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0,2024,7,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0,2024,7,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0,2024,22,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0,2024,12,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0,2024,19,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0,2024,14,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN,2024,4,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0,2024,7,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0,2024,4,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0,2024,22,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0,2024,23,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN,2024,18,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0,2024,23,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0,2024,19,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0,2024,21,82 days

In [141]:
instructor_group = df.groupby('Instructor')

instructor_group

In [142]:
for instructor , df_ins in instructor_group : 
    print(instructor)
    display(df_ins)

Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Date,Total time taken to finish
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0,2024,1,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0,2024,7,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0,2024,7,43 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0,2024,19,61 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0,2024,7,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0,2024,4,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0,2024,22,84 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN,2024,18,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0,2024,23,89 days

Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Date,Total time taken to finish
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0,2024,11,88 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0,2024,5,80 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0,2024,12,117 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0,2024,14,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN,2024,4,82 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0,2024,19,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0,2024,21,82 days

Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN,2024,1,113 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0,2024,8,92 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0,2024,22,40 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0,2024,23,90 days

In [143]:
# df.min()


instructor_group.min()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks,Enrollment Year,Enrollment Date,Total time taken to finish
Instructor,,,,,,,,,,
Mr. David,PH0005,Afsana Mimi,Completed,2024-01-04,2024-03-16,Chattogram,248.0,2024,1,43 days
Mr. Karim,PH0002,Faria Rahman,Completed,2024-02-12,2024-06-08,Dhaka,253.0,2024,4,80 days
Ms. Salma,PH0001,Alif Rahman,Completed,2024-03-22,2024-05-01,Dhaka,234.0,2024,1,40 days

In [144]:
instructor_group.describe()

           EnrollmentDate                                                      \
                    count                           mean                  min
Instructor
Mr. David               9            2024-04-22 13:20:00  2024-01-04 00:00:00
Mr. Karim               7  2024-05-30 03:25:42.857142784  2024-02-12 00:00:00
Ms. Salma               4            2024-05-13 18:00:00  2024-03-22 00:00:00

                                                                           \
                            25%                  50%                  75%
Instructor
Mr. David   2024-02-01 00:00:00  2024-06-07 00:00:00  2024-06-19 00:00:00
Mr. Karim   2024-04-01 00:00:00  2024-07-05 00:00:00  2024-07-28 00:00:00
Ms. Salma   2024-03-22 18:00:00  2024-04-15 00:00:00  2024-06-06 00:00:00

                                     FinishedDate  \
                            max  std        count
Instructor
Mr. David   2024-09-07 00:00:00  NaN            9
Mr. Karim   2024-08-11 00:00:00  NaN            7
Ms. Salma   2024-09-01 00:00:00  NaN            4

                                           ... Enrollment Date             \
                                     mean  ...             max        std
Instructor                                 ...
Mr. David             2024-07-05 02:40:00  ...            23.0   8.411302
Mr. Karim   2024-09-01 03:25:42.857142784  ...            21.0   6.421689
Ms. Salma             2024-08-05 12:00:00  ...            23.0  10.785793

           Total time taken to finish                                      \
                                count              mean               min
Instructor
Mr. David                           9  73 days 13:20:00  43 days 00:00:00
Mr. Karim                           7  94 days 00:00:00  80 days 00:00:00
Ms. Salma                           4  83 days 18:00:00  40 days 00:00:00

                                                                   \
                         25%               50%                75%
Instructor
Mr. David   58 days 00:00:00  76 days 00:00:00   84 days 00:00:00
Mr. Karim   82 days 00:00:00  88 days 00:00:00  103 days 00:00:00
Ms. Salma   77 days 12:00:00  91 days 00:00:00   97 days 06:00:00


                          max                         std
Instructor
Mr. David   115 days 00:00:00  21 days 12:42:45.670041246
Mr. Karim   120 days 00:00:00  17 days 01:52:40.910298182
Ms. Salma   113 days 00:00:00  30 days 23:11:35.199023911

[3 rows x 48 columns]

In [145]:
mean_marks = instructor_group['Total Marks'].mean()

mean_marks

Instructor
Mr. David    270.375000
Mr. Karim    274.166667
Ms. Salma    249.666667
Name: Total Marks, dtype: float64

In [146]:
df['Total Marks']= df['Total Marks'].fillna(df['Instructor'].map(mean_marks)) 

df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Year,Enrollment Date,Total time taken to finish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,249.666667,2024,1,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.000000,2024,11,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.000000,2024,8,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.000000,2024,5,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.000000,2024,1,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.000000,2024,7,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.000000,2024,7,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.000000,2024,22,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.000000,2024,12,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.000000,2024,19,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.000000,2024,14,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,274.166667,2024,4,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.000000,2024,7,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.000000,2024,4,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.000000,2024,22,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.000000,2024,23,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,270.375000,2024,18,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.000000,2024,23,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.000000,2024,19,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.000000,2024,21,82 days