In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/phitronio/AI-ML-Batch-2-Machine-Learning/refs/heads/main/Module%2007/titanic_data_updated.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.drop(['PassengerId','Name','Ticket',],axis=1,inplace=True)
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [5]:
X = df.drop(["Survived"],axis=1)
y = df["Survived"]

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,train_size=0.2)
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare    Cabin Embarked
761   third    male  41.0      0      0    7.1250      NaN        S
645   first    male  48.0      1      0   76.7292      D33        C
754  second  female  48.0      1      2   65.0000      NaN        S
556   first  female  48.0      1      0   39.6000      A16        C
850   third    male   4.0      4      2   31.2750      NaN        S
..      ...     ...   ...    ...    ...       ...      ...      ...
106   third  female  21.0      0      0    7.6500      NaN        S
270   first    male   NaN      0      0   31.0000      NaN        S
860   third    male  41.0      2      0   14.1083      NaN        S
435   first  female  14.0      1      2  120.0000  B96 B98        S
102   first    male  21.0      0      1   77.2875      D26        S

[178 rows x 8 columns]

In [6]:
from sklearn.impute import SimpleImputer
age_imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
age_imputer.fit(X_train[["Age"]])

X_train["Age"] =age_imputer.transform(X_train[["Age"]]).ravel()
X_train.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       132
Embarked      0
dtype: int64

In [7]:
X_test['Age'] = age_imputer.transform(X_test[['Age']])

X_test.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Cabin       555
Embarked      2
dtype: int64

In [8]:
embarked_imputer = SimpleImputer(missing_values=np.nan , strategy='most_frequent')

embarked_imputer.fit(X_train[['Embarked']])

# transform both train and test data

X_train['Embarked']= embarked_imputer.transform(X_train[['Embarked']]).ravel()
X_test['Embarked'] = embarked_imputer.transform(X_test[['Embarked']]).ravel()

In [9]:
cabin_imputer = SimpleImputer(missing_values=np.nan , strategy='constant',fill_value='Missing',add_indicator=True)

cabin_imputer.fit(X_train[['Cabin']])

# transform both train and test data

X_train[['Cabin','cabin_missing_indicator']]= cabin_imputer.transform(X_train[['Cabin']])
X_test[['Cabin','cabin_missing_indicator']] = cabin_imputer.transform(X_test[['Cabin']])

In [10]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_missing_indicator
761,third,male,41.000000,0,0,7.1250,Missing,S,True
645,first,male,48.000000,1,0,76.7292,D33,C,False
754,second,female,48.000000,1,2,65.0000,Missing,S,True
556,first,female,48.000000,1,0,39.6000,A16,C,False
850,third,male,4.000000,4,2,31.2750,Missing,S,True
...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,True
270,first,male,30.355172,0,0,31.0000,Missing,S,True
860,third,male,41.000000,2,0,14.1083,Missing,S,True
435,first,female,14.000000,1,2,120.0000,B96 B98,S,False
102,first,male,21.000000,0,1,77.2875,D26,S,False

In [11]:
mean_of_age = X_train["Age"].mean()
std_of_age = X_train["Age"].std()
X_train['zscore_age'] =(X_train['Age']-mean_of_age)/std_of_age
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_missing_indicator,zscore_age
761,third,male,41.000000,0,0,7.1250,Missing,S,True,0.920139
645,first,male,48.000000,1,0,76.7292,D33,C,False,1.525219
754,second,female,48.000000,1,2,65.0000,Missing,S,True,1.525219
556,first,female,48.000000,1,0,39.6000,A16,C,False,1.525219
850,third,male,4.000000,4,2,31.2750,Missing,S,True,-2.278141
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,True,-0.808661
270,first,male,30.355172,0,0,31.0000,Missing,S,True,0.000000
860,third,male,41.000000,2,0,14.1083,Missing,S,True,0.920139
435,first,female,14.000000,1,2,120.0000,B96 B98,S,False,-1.413741
102,first,male,21.000000,0,1,77.2875,D26,S,False,-0.808661

In [ ]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
pclass_encoder = OrdinalEncoder(
    categories=[['third','second','first']]
)

pclass_encoder.fit(X_train[['Pclass']])

X_train['encoded_Pclass'] = pclass_encoder.transform(X_train[['Pclass']]).ravel()
X_test['encoded_Pclass'] = pclass_encoder.transform(X_test[['Pclass']]).ravel()