# 🧠 Pandas → LeetCode Mastery Guide (Pro Notes)

This notebook is designed to bridge the gap between:
- Knowing Pandas
- Solving real interview / LeetCode problems

👉 Focus: Thinking process + Patterns + Real-world logic

---

## 🚀 Core Truth

Most developers fail not because they don't know Pandas,
but because they cannot translate problems into steps.

### 🔑 Key Skill:
Convert English → Steps → Pandas Code

# 🧩 Step-by-Step Problem Solving Framework

Whenever you see a problem:

### Step 1: Understand in plain English
Example:
> Find highest salary per department

### Step 2: Break into steps
- Group by department
- Find max salary

### Step 3: Convert to Pandas

👉 This is the MOST IMPORTANT SKILL

# 🔥 Core Patterns (90% of LeetCode Pandas)

Master these patterns and you can solve most problems.

In [1]:
import pandas as pd

# Sample Data
df = pd.DataFrame({
    'employee': ['A', 'B', 'C', 'D', 'E'],
    'department': ['HR', 'HR', 'IT', 'IT', 'IT'],
    'salary': [5000, 6000, 7000, 8000, 8000],
    'age': [25, 30, 35, 40, 28]
})

df

  employee department  salary  age
0        A         HR    5000   25
1        B         HR    6000   30
2        C         IT    7000   35
3        D         IT    8000   40
4        E         IT    8000   28

## 1️⃣ Filtering Pattern

👉 Used when condition-based selection is needed

Example:
Find employees with salary > 6000

In [2]:
df[df['salary'] > 6000]

  employee department  salary  age
2        C         IT    7000   35
3        D         IT    8000   40
4        E         IT    8000   28

## 2️⃣ GroupBy + Aggregation

👉 Used when summarizing data

Example:
Average salary per department

In [3]:
df.groupby('department')['salary'].mean()

department
HR    5500.000000
IT    7666.666667
Name: salary, dtype: float64

## 3️⃣ Top N / Sorting

👉 Used for ranking problems

Example:
Top 2 highest salaries

In [4]:
df.sort_values('salary', ascending=False).head(2)

  employee department  salary  age
4        E         IT    8000   28
3        D         IT    8000   40

## 4️⃣ Ranking / Window Functions

👉 Important for interview problems

Example:
Rank employees by salary

In [5]:
df['rank'] = df['salary'].rank(method='dense', ascending=False)
df

  employee department  salary  age  rank
0        A         HR    5000   25   4.0
1        B         HR    6000   30   3.0
2        C         IT    7000   35   2.0
3        D         IT    8000   40   1.0
4        E         IT    8000   28   1.0

## 5️⃣ Transform (VERY IMPORTANT)

👉 Used when you need group results back to original rows

Example:
Find highest salary per department AND show employees

In [6]:
max_salary = df.groupby('department')['salary'].transform('max')
df[df['salary'] == max_salary]

  employee department  salary  age  rank
1        B         HR    6000   30   3.0
3        D         IT    8000   40   1.0
4        E         IT    8000   28   1.0

# 🧪 Real LeetCode Style Problems

## Problem 1: Second Highest Salary

### Thinking Process:
- Remove duplicates
- Sort descending
- Pick second value

In [ ]:
df['salary'].drop_duplicates().sort_values(ascending=False).iloc[1]

## Problem 2: Duplicate Emails (Concept)

### Thinking:
- Find duplicates
- Count occurrences

In [ ]:
df['employee'].value_counts()[lambda x: x > 1]

# ⚠️ Common Mistakes

❌ Using apply() everywhere (slow)
❌ Not breaking problem into steps
❌ Jumping to hard problems too early

👉 Always think first, code later

# 🧠 Pro Tips

### 🔥 Pattern Mapping Cheat Sheet

| Problem Type | Solution Pattern |
|-------------|------------------|
| Highest per group | groupby + transform |
| Ranking | rank() |
| Top N | sort_values + head |
| Duplicates | value_counts / duplicated |
| Running total | cumsum |

---

## 🚀 Final Advice

You don't need more Pandas knowledge.

You need:
👉 Pattern recognition
👉 Step-by-step thinking

Practice daily and rewrite solutions from memory.