# 🧠 Pandas Self Join (merge) — Full Mastery Guide

This notebook explains:
- What is merge (JOIN)
- Why we need it
- Step-by-step execution
- Visual understanding
- Real LeetCode problem solution

---

## 🎯 Goal

Find employees who earn more than their manager

In [1]:
import pandas as pd

df = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"],
    "salary": [70000, 80000, 60000, 90000],
    "managerId": [3, 4, None, None]
})

df

   id   name  salary  managerId
0   1    Joe   70000        3.0
1   2  Henry   80000        4.0
2   3    Sam   60000        NaN
3   4    Max   90000        NaN

# 🔍 Step 1: Understand the Problem

We need:
- Employee salary
- Manager salary

❌ Problem: Manager salary is NOT directly in the row

👉 So we must connect rows together

# 🔗 Step 2: What is merge()?

merge = JOIN (like SQL)

It combines two tables based on matching columns.

### Simple Example

In [2]:
left = pd.DataFrame({
    "id": [1, 2],
    "name": ["A", "B"]
})

right = pd.DataFrame({
    "id": [1, 2],
    "salary": [100, 200]
})

left.merge(right, on="id")

   id name  salary
0   1    A     100
1   2    B     200

👉 This joins tables where `id` matches

# 🔁 Step 3: Self Join Concept

We are merging the SAME table with itself.

Why?
- Employee row has managerId
- Manager is ALSO in same table

👉 So we match:
employee.managerId = manager.id

In [3]:
merged = df.merge(
    df,
    left_on="managerId",   # employee side
    right_on="id",        # manager side
    suffixes=("_emp", "_mgr")
)

merged

,id_emp,name_emp,salary_emp,managerId_emp,id_mgr,name_mgr,salary_mgr,managerId_mgr
0,1,Joe,70000,3.0,3,Sam,60000,NaN
1,2,Henry,80000,4.0,4,Max,90000,NaN

# 🧾 What happened after merge?

Now we have:

- employee data (suffix _emp)
- manager data (suffix _mgr)

Example row:

| name_emp | salary_emp | name_mgr | salary_mgr |
|----------|-----------|----------|------------|
| Joe      | 70000     | Sam      | 60000      |

🔥 Now we can compare easily!

# ⚖️ Step 4: Filtering Condition

We only want:

employee.salary > manager.salary

In [4]:
result = merged[merged["salary_emp"] > merged["salary_mgr"]]
result

,id_emp,name_emp,salary_emp,managerId_emp,id_mgr,name_mgr,salary_mgr,managerId_mgr
0,1,Joe,70000,3.0,3,Sam,60000,NaN

# 🧾 Step 5: Select Final Column

We only need employee name

In [5]:
final = result[["name_emp"]].rename(columns={"name_emp": "Employee"})
final

  Employee
0      Joe

# 🔥 Final Answer

Joe earns more than his manager.

# 🧠 Deep Understanding Summary

### Why merge?
Because data you need is in another row

### Why suffixes?
To avoid column name conflict

### Why filtering?
To apply condition after joining

---

## 🚀 Pattern Learned

👉 Self Join Pattern

Used when:
- manager
- parent
- hierarchy

---

## ⚠️ Common Mistake

❌ Trying to compare without merge

👉 You must JOIN first

---

## 🎯 Practice Task

Try modifying:
- Find employees earning LESS than manager
- Find employees with NO manager

👉 This will make you strong